name: neutron
version: ocata
summary: OpenStack Network Service (neutron)
description: OpenStack Network Service (neutron)
confinement: strict
grade: devel

apps:
  api:
    command: snap-openstack neutron-server
    daemon: simple
    plugs:
      - network-bind
  manage:
    command: snap-openstack neutron-db-manage
    aliases:
      - neutron-db-manage
    plugs:
      - network

parts:
  neutron:
    after: [patches]
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/neutron/neutron-stable-ocata.tar.gz
    python-packages:
      - pymysql
      - python-memcached
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/ocata/upper-constraints.txt
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
    install: |
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/paste/__init__.py
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/repoze/__init__.py
      cd $SNAPCRAFT_PART_INSTALL
      export PATCH_DIR="../../patches/src"
      patch -p4 < $PATCH_DIR/oslo-config-dirs.patch
      cd -
  patches:
    plugin: dump
    source: patches
  templates:
    after: [neutron]
    plugin: dump
    source: snap
  # TODO: replace below with scriplets once implemented in snapcraft
  config:
    after: [neutron]
    plugin: dump
    source: http://tarballs.openstack.org/neutron/neutron-stable-ocata.tar.gz
    organize:
      etc/*.conf: etc/neutron/
      etc/*.ini: etc/neutron/
      etc/*.json: etc/neutron/
      etc/rootwrap.d/*: etc/neutron/rootwrap.d/
    filesets:
      etc:
        - etc/neutron/*
    stage: [$etc]
    prime: [$etc]
