name: neutron
version: ocata
summary: OpenStack Network Service (neutron)
description: OpenStack Network Service (neutron)
confinement: classic
grade: devel

apps:
  api:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-server
    daemon: simple
  manage:
    command: >
      env PYTHONPATH=$PYTHONPATH:$SNAP/lib/python2.7/site-packages
      $SNAP/usr/bin/python2 $SNAP/bin/snap-openstack neutron-db-manage
    aliases:
      - neutron-db-manage

parts:
  neutron:
    after: [python]
    plugin: python
    python-version: python2
    source: http://tarballs.openstack.org/neutron/neutron-stable-ocata.tar.gz
    python-packages:
      - pymysql
      - python-memcached
      - git+https://github.com/openstack/snap.openstack#egg=snap.openstack
    constraints: https://raw.githubusercontent.com/openstack/requirements/stable/ocata/upper-constraints.txt
    build-packages:
      - gcc
      - libffi-dev
      - libssl-dev
    stage:
      - -usr/bin/2to3
      - -usr/bin/pydoc
      - -usr/bin/python2.7
      - -usr/lib/python2.7
    install: |
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/paste/__init__.py
      touch $SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages/repoze/__init__.py
      export SNAP_ROOT="../../../"
      export SNAP_SITE_PACKAGES="$SNAPCRAFT_PART_INSTALL/lib/python2.7/site-packages"
      patch -d $SNAP_SITE_PACKAGES -p1 < $SNAP_ROOT/patches/oslo-config-dirs.patch
  templates:
    after: [neutron]
    plugin: dump
    source: snap
  config:
    after: [neutron]
    plugin: dump
    source: http://tarballs.openstack.org/neutron/neutron-stable-ocata.tar.gz
    organize:
      etc/*.conf: etc/neutron/
      etc/*.ini: etc/neutron/
      etc/*.json: etc/neutron/
      etc/rootwrap.d/*: etc/neutron/rootwrap.d/
    filesets:
      etc:
        - etc/neutron/*
    stage: [$etc]
    prime: [$etc]
  python:
    source: https://www.python.org/ftp/python/2.7.13/Python-2.7.13.tar.xz
    plugin: autotools
    configflags:
      - --prefix=/usr
      - --enable-shared
      - --enable-unicode=ucs4
    build-packages:
      - libssl-dev
    prime:
      - -usr/include
    install:
      $SNAPCRAFT_PART_INSTALL/usr/bin/python2 -m ensurepip
